[
  {
    key: "name",
    name: "Name",
    required: true,
    fieldType: "text",
    type: "text",
    options: [],
    showError: false,
    errorMsg: "This Field is Required",
  },
  {
    key: "designation",
    name: "Designation",
    required: true,
    fieldType: "text",
    type: "text",
    options: [],
    showError: false,
    errorMsg: "This Field is Required",
  },
  {
    key: "organisation",
    name: "Organisation",
    required: true,
    fieldType: "text",
    type: "text",
    options: [],
    showError: false,
    errorMsg: "This Field is Required",
  },
  {
    key: "membership_category",
    name: "Membership Category",
    fieldType: "select",
    required: true,
    type: "select",
    options: [
      {
        key: "select_membership_category",
        value: " ",
        label: "Select Membership Category",
      },
      {
        key: "life_fellow",
        value: "Life Fellow",
        label: "Life Fellow",
      },
      {
        key: "life_member",
        value: "Life Member",
        label: "Life Member",
      },
      {
        key: "associate_member",
        value: "Associate Member",
        label: "Associate Member",
      },
      {
        key: "life_corporate_member",
        value: "Life Corporate Member",
        label: "Life Corporate Member",
      },
      {
        key: "honorary_fellowship",
        value: "Life Corporate Member",
        label: "Life Corporate Member",
      },
      {
        key: "affiliate_member",
        value: "Affiliate Member",
        label: "Affiliate Member",
      },
    ],
    value: "",
    showError: false,
    errorMsg: "This Field is Required",
  },
  {
    key: "address",
    name: "Address",
    fieldType: "text",
    required: true,
    type: "text",
    options: [],
    showError: false,
    errorMsg: "This Field is Required",
  },
  {
    key: "city",
    name: "City",
    fieldType: "text",
    required: true,
    type: "text",
    options: [],
    showError: false,
    errorMsg: "This Field is Required",
  },
  {
    key: "pincode",
    name: "Pincode",
    fieldType: "number",
    required: true,
    type: "text",
    options: [],
    showError: false,
    errorMsg: "This Field is Required",
  },
  {
    key: "state",
    name: "State",
    fieldType: "text",
    required: true,
    type: "text",
    options: [],
    showError: false,
    errorMsg: "This Field is Required",
  },
  {
    key: "country",
    name: "Country",
    fieldType: "text",
    required: true,
    type: "text",
    options: [],
    showError: false,
    errorMsg: "This Field is Required",
  },
  {
    key: "mobile",
    name: "Mobile",
    required: true,
    fieldType: "number",
    type: "text",
    options: [],
    showError: false,
    errorMsg: "This Field is Required",
  },
  {
    key: "email",
    name: "Email",
    fieldType: "email",
    required: true,
    type: "text",
    options: [],
    showError: false,
    errorMsg: "This Field is Required",
  },
];
