import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "./UIComponent/Navbar/Navbar";
import Footer from "./UIComponent/Footer/Footer";
import { SpeedInsights } from "@vercel/speed-insights/next";
import { Analytics } from "@vercel/analytics/react";
import {
  getVisitorCounter,
  updateVisitorCounter,
} from "./backend/helper/visitor_helper/visitor_counter_helper";
import { cookies } from "next/headers";
import { ENVIROMENT } from "./backend/constant";
import DownloadBrochureButton from "./UIComponent/buttons/download-brochure";
const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Welcome-BESINDIA",
  description: "Generated by create next app",
};

export default async function RootLayout({ children }: any) {
  let intitalCounter = await getVisitorCounter();
  const cookieStore = cookies();
  let besSessionCookies = cookieStore.get("updateCounter")?.value;

  if (besSessionCookies) {
    updateVisitorCounter();
  }

  return (
    <html lang="en" className="h-full">
      <body className="h-full overflow-hidden">
        <Navbar />
        <div className="overflow-auto inner_page scroll-smooth">
          <div className="body_page">{children}</div>
          <DownloadBrochureButton />
          <Footer initialCount={intitalCounter} />
        </div>
        {ENVIROMENT === "production" && <Analytics />}
        {ENVIROMENT === "production" && <SpeedInsights />}
      </body>
    </html>
  );
}
