export const bookMySpaceTemplateVisitor = (
  userDetails: any,
  type = "We have SuccessFully Registed your details"
) => {
  let userStr = "";

  for (let key in userDetails) {
    let temp = `<li><strong>${key}:</strong> ${userDetails[key]}</li>`;
    userStr += temp;
  }

  return `
<body style="margin: 0; padding: 0; background-color: #f4f4f4; font-family: Arial, sans-serif;">
  <table width="100%" border="0" cellspacing="0" cellpadding="0">
    <tr>
      <td align="center" style="padding: 20px 0;">
        <table width="100%" border="0" cellspacing="0" cellpadding="0" style="max-width: 600px; background-color: #fff; border-radius: 5px; box-shadow: 0 0 10px rgba(0, 0, 0, 0.1);">
        
          <tr>
            <td style="padding: 20px;">
              <p style="font-size: 16px; line-height: 1.5;">
           ${type}
              </p>
              <ul style="font-size: 16px; line-height: 1.5; padding-left: 20px; margin: 0;">
                ${userStr}
              </ul>
            </td>
          </tr>
          <tr>
            <td align="center" style="padding: 10px; font-size: 12px; color: #888;">
              <p style="margin: 0;">This email was automatically generated by BookMySpace.</p>
            </td>
          </tr>
        </table>
      </td>
    </tr>
  </table>
</body>
`;
};
